on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  pr:pathum25 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install virtualenv
    - run: make
    - run: make push
      env:
        GH_TOKEN: ${{ 5e3f7554-7ddd-4da9-803e-5d11d32002fc}
